"""
API surface for the Android companion app <-> Django CRM calling sync,
plus a secure n8n-facing daily report endpoint. Mirrors the existing
crm/api.py n8n integration: same "reject unless proven" style, same JSON
error shape, same idempotency-via-unique-external-id pattern.

Endpoints (see crm/urls.py):
  POST /api/calling/pair/   — Android app redeems a one-time pairing code
                              (generated by an admin in the CRM) for a
                              permanent bearer token. See CallDevice.
  POST /api/calling/sync/   — Android app pushes new call-log events.
                              Authenticated with "Authorization: Bearer <token>".
  GET  /api/calling/daily/  — n8n pulls the daily rollup, same
                              X-N8N-API-KEY header n8n already sends to
                              crm/api.py.
"""
import datetime
import json

from django.conf import settings
from django.http import JsonResponse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET, require_POST

from . import calling_analytics as analytics
from .models import CallDevice, CallRecord, Contact, Lead, PrivilegedNumber, normalize_phone, user_label
from .services import log_activity

MAX_BATCH = 500


def _error(message, status=400, **extra):
    payload = {"success": False, "message": message}
    payload.update(extra)
    return JsonResponse(payload, status=status)


def _check_n8n_key(request):
    expected = getattr(settings, "N8N_API_KEY", "")
    provided = request.headers.get("X-N8N-API-KEY", "")
    return bool(expected) and provided == expected


def _bearer_token(request):
    header = request.headers.get("Authorization", "")
    return header[7:].strip() if header.startswith("Bearer ") else ""


def _parse_epoch_ms(raw):
    """Android sends System.currentTimeMillis()-style epoch milliseconds
    (straight from CallLog.Calls.DATE) — the one unambiguous format
    regardless of the phone's locale/timezone settings."""
    if raw in (None, ""):
        return None
    try:
        return datetime.datetime.fromtimestamp(int(raw) / 1000, tz=datetime.timezone.utc)
    except (TypeError, ValueError, OverflowError):
        return None


def _duration_label(total_seconds):
    m, s = divmod(int(total_seconds or 0), 60)
    return f"{m}m {s:02d}s" if m else f"{s}s"


@csrf_exempt
@require_POST
def pair_device(request):
    try:
        data = json.loads(request.body or "{}")
    except json.JSONDecodeError:
        return _error("Request body must be valid JSON.")

    code = str(data.get("pairing_code") or "").strip()
    android_device_id = str(data.get("device_id") or "").strip()
    if len(code) != 6 or not code.isdigit():
        return _error("A 6-digit pairing_code is required.")
    if not android_device_id:
        return _error("device_id is required.")

    try:
        device = CallDevice.objects.select_related("staff").get(
            pairing_code=code, pairing_code_expires__gte=timezone.now(),
        )
    except CallDevice.DoesNotExist:
        return _error("Pairing code is invalid or has expired. Ask your admin for a new one.", status=404)

    raw_token = device.complete_pairing(android_device_id)
    return JsonResponse(
        {
            "success": True,
            # Shown exactly once. The app must store this in EncryptedSharedPreferences
            # (or the Android Keystore) and never ask the server for it again.
            "token": raw_token,
            "staff_name": user_label(device.staff),
            "device_label": device.label,
        },
        status=201,
    )


@csrf_exempt
@require_POST
def sync_calls(request):
    device = CallDevice.authenticate(_bearer_token(request))
    if device is None:
        return _error("Invalid, revoked, or expired device token.", status=401)

    try:
        data = json.loads(request.body or "{}")
    except json.JSONDecodeError:
        return _error("Request body must be valid JSON.")

    events = data.get("calls")
    if not isinstance(events, list):
        return _error("Body must include a 'calls' array.")
    if len(events) > MAX_BATCH:
        return _error(f"Too many events in one batch (max {MAX_BATCH}).")

    device.last_seen = timezone.now()
    device.save(update_fields=["last_seen"])

    # Idempotency: look up which external_call_ids already exist BEFORE
    # inserting anything, so a retried/duplicate-delivered batch (e.g. the
    # phone went offline mid-sync and resent the same events) never
    # double-counts a call. The unique DB constraint on external_call_id
    # is the real guarantee; this lookup just avoids a wasted bulk_create.
    incoming_ids = [str(e.get("external_call_id") or "").strip() for e in events]
    incoming_ids = [i for i in incoming_ids if i]
    existing_ids = set(
        CallRecord.objects.filter(external_call_id__in=incoming_ids).values_list("external_call_id", flat=True)
    )

    # One cheap query for the whole batch — never per-event — so a privileged
    # number (owner/Jiju) is excluded from CRM entirely, whatever staff/device
    # the call came from.
    privileged_numbers = PrivilegedNumber.active_normalized_set()

    to_create, skipped, ignored, errors = [], 0, 0, []
    for event in events:
        ext_id = str(event.get("external_call_id") or "").strip()
        if not ext_id:
            errors.append({"error": "missing external_call_id", "event": event})
            continue
        if ext_id in existing_ids:
            skipped += 1
            continue

        started_at = _parse_epoch_ms(event.get("started_at"))
        if started_at is None:
            errors.append({"error": "missing/invalid started_at", "external_call_id": ext_id})
            continue

        direction = event.get("direction") if event.get("direction") in (
            CallRecord.DIRECTION_OUTGOING, CallRecord.DIRECTION_INCOMING,
        ) else CallRecord.DIRECTION_OUTGOING
        status = event.get("status") if event.get("status") in dict(CallRecord.STATUS_CHOICES) else CallRecord.STATUS_UNKNOWN
        duration = max(0, int(event.get("duration_seconds") or 0))
        phone_number = str(event.get("phone_number") or "")[:20].strip()
        phone_norm = normalize_phone(phone_number)

        if not phone_norm or phone_norm in privileged_numbers:
            # No number, or an owner/Jiju number: never touches the CRM at
            # all — not stored, not counted, not eligible for any status
            # change. The real phone call itself is untouched by any of this.
            ignored += 1
            continue

        # CRM assignment is the single source of truth for whether THIS call,
        # from THIS staff member's device, is eligible for CRM sync at all.
        # A lead/contact that matches the number but is assigned to someone
        # else (or unassigned) is a personal/unrelated call as far as the
        # CRM is concerned — ignored completely, never stored.
        lead = (
            Lead.objects.filter(phone_normalized=phone_norm, assigned_to_id=device.staff_id)
            .order_by("-created_at").first()
        )
        contact = (
            Contact.objects.filter(phone_normalized=phone_norm, current_assigned_to_id=device.staff_id)
            .order_by("-id").first()
            if lead is None else None
        )
        if lead is None and contact is None:
            ignored += 1
            continue

        to_create.append(CallRecord(
            staff=device.staff, device=device, lead=lead, contact=contact,
            phone_number=phone_number, phone_normalized=phone_norm,
            direction=direction, status=status,
            started_at=started_at,
            ended_at=started_at + datetime.timedelta(seconds=duration) if duration else started_at,
            duration_seconds=duration,
            external_call_id=ext_id, source="android",
        ))

    if to_create:
        # ignore_conflicts=True makes the unique external_call_id constraint
        # the final word on duplicates even if two sync requests race — a
        # single bulk INSERT stays cheap however large call volume grows.
        CallRecord.objects.bulk_create(to_create, ignore_conflicts=True)

        for record in to_create:
            # Auto timeline entry on the matched lead/contact only
            # (requirement #10 — this never runs for the manual "Call
            # Completed" button, which writes kind="call"; this always
            # writes kind="call_auto" so the two can never be confused
            # when counting real calls).
            try:
                when = timezone.localtime(record.started_at).strftime("%d %b, %I:%M %p")
                direction_label = "Outgoing" if record.direction == CallRecord.DIRECTION_OUTGOING else "Incoming"
                log_activity(
                    record.staff, "call_auto",
                    f"{direction_label} call — {record.get_status_display()} "
                    f"({when}, {_duration_label(record.duration_seconds)})",
                    lead=record.lead, contact=record.contact,
                )
            except Exception:
                pass  # never fail the sync because of timeline bookkeeping

            # ================================================================
            # THE ONLY automatic status transition anywhere in this system:
            # NEW -> CONTACTED, and ONLY when ALL of these are true:
            #   - direction is OUTGOING (an incoming call never triggers this)
            #   - Android reliably reported ANSWERED (never inferred from
            #     duration thresholds, never on MISSED/NO_ANSWER/REJECTED/
            #     BUSY/FAILED/NOT_CONNECTED/UNKNOWN)
            #   - the number is an eligible CRM lead/contact assigned to this
            #     staff member (already guaranteed above — ineligible calls
            #     never reach this loop at all)
            # Every other status (DOCUMENT PENDING, APPROVED, ...) is left
            # completely untouched, and repeat answered calls on an already-
            # CONTACTED lead just add another CallRecord with no status write.
            # The conditional .update(status=... , status=NEW) is a single
            # atomic UPDATE ... WHERE status='new' — the DB row lock makes
            # this safe against two answered-call events for the same lead
            # racing each other, and naturally idempotent if a duplicate
            # event ever slipped past the external_call_id check.
            # ================================================================
            if record.direction == CallRecord.DIRECTION_OUTGOING and record.status == CallRecord.STATUS_ANSWERED:
                if record.lead_id is not None:
                    moved = Lead.objects.filter(pk=record.lead_id, status=Lead.STATUS_NEW).update(
                        status=Lead.STATUS_CONTACTED
                    )
                    if moved:
                        try:
                            log_activity(
                                record.staff, "status",
                                "Status changed: New → Contacted (auto — answered outgoing call)",
                                lead=record.lead,
                            )
                        except Exception:
                            pass
                elif record.contact_id is not None:
                    moved = Contact.objects.filter(pk=record.contact_id, status=Contact.STATUS_NEW).update(
                        status=Contact.STATUS_CONTACTED
                    )
                    if moved:
                        try:
                            log_activity(
                                record.staff, "status",
                                "Status changed: New → Contacted (auto — answered outgoing call)",
                                contact=record.contact,
                            )
                        except Exception:
                            pass

    return JsonResponse(
        {"success": True, "created": len(to_create), "skipped": skipped, "ignored": ignored, "errors": errors},
        status=201,
    )


@require_GET
def daily_report(request):
    if not _check_n8n_key(request):
        return _error("Invalid or missing API key.", status=401)
    date_from, date_to = analytics.date_range_for_preset(request.GET)
    return JsonResponse({
        "success": True,
        "date_from": date_from, "date_to": date_to,
        "results": analytics.daily_report(request.GET),
    })
