# Generated by Django 5.2.17 on 2026-09-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='external_submission_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='form_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('docs_pending', 'Documents Pending'), ('docs_complete', 'Documents Complete'), ('meeting_requested', 'Meeting Requested'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
