# Generated by Django 5.2.17 on 2026-09-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_external_submission_id_lead_form_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='n8n_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='n8n_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='n8n_sync_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
