# Generated by Django 5.2.17 on 2026-09-16 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_n8n_error_lead_n8n_last_sync_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='reference_by_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text="Internal CRM staff assignment (optional, not on the n8n-matching form). Set manually elsewhere if/when needed; unrelated to the free-text 'Assigned To' field the original n8n form collects.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reference_by',
            field=models.ForeignKey(blank=True, help_text="Internal CRM ownership only (drives 'My Leads' + edit/delete permissions). Auto-set to the logged-in staff member who creates the lead — not shown on the Add/Edit Lead form.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
