# Generated by Django 5.2.17 on 2026-09-24 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_assigned_to_name_lead_reference_by_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True, help_text='Counts toward completion.')),
                ('is_default', models.BooleanField(default=True, help_text='Appears on every lead. Non-default items can be added per lead.')),
                ('is_archived', models.BooleanField(default=False, help_text='Soft-deleted: hidden everywhere but history keeps it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportReviewRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('decision', models.CharField(blank=True, choices=[('', 'Undecided'), ('skip', 'Skip'), ('update', 'Update existing'), ('new', 'Import as new')], default='', max_length=10)),
                ('applied', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportRowError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('field', models.CharField(blank=True, max_length=60)),
                ('problem', models.CharField(max_length=200)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('raw', models.JSONField(blank=True, default=list)),
                ('stage', models.CharField(default='analyze', max_length=10)),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who physically created the row. Never changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='followup_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='followup_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('done', 'Done')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='interest',
            field=models.CharField(blank=True, choices=[('', 'Not recorded'), ('interested', 'Interested'), ('not_interested', 'Not interested')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_followup_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_followup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='original_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originally_assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('summary', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('target_type', models.CharField(blank=True, max_length=30)),
                ('target_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='queued', max_length=10)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('work_profile', models.CharField(blank=True, max_length=200)),
                ('income', models.CharField(blank=True, max_length=100)),
                ('requirement', models.CharField(blank=True, max_length=200)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not interested'), ('callback', 'Call back'), ('converted', 'Converted to lead')], db_index=True, default='new', max_length=20)),
                ('next_followup_date', models.DateField(blank=True, db_index=True, null=True)),
                ('next_followup_time', models.TimeField(blank=True, null=True)),
                ('followup_notes', models.TextField(blank=True)),
                ('followup_status', models.CharField(blank=True, default='', max_length=10)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('current_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
                ('original_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reference_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assign', 'Assigned'), ('reassign', 'Reassigned'), ('transfer', 'Transferred')], max_length=10)),
                ('from_name', models.CharField(blank=True, max_length=150)),
                ('to_name', models.CharField(blank=True, max_length=150)),
                ('changed_by_name', models.CharField(blank=True, max_length=150)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='crm.lead')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='crm.contact')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.contact'),
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('old_received', models.BooleanField(default=False)),
                ('new_received', models.BooleanField(default=False)),
                ('changed_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_history', to='crm.lead')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.documenttype')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('stored_path', models.CharField(blank=True, max_length=500)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('mapped', 'Columns mapped'), ('analyzing', 'Validating'), ('analyzed', 'Ready to import'), ('importing', 'Importing'), ('review', 'Duplicates need review'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=12)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('source_label', models.CharField(blank=True, max_length=100)),
                ('duplicate_policy', models.CharField(choices=[('skip', 'Skip duplicates'), ('update', 'Update existing record'), ('new', 'Import as new record'), ('review', 'Review duplicates')], default='skip', max_length=10)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('analysis_new', models.PositiveIntegerField(default=0)),
                ('analysis_duplicates', models.PositiveIntegerField(default=0)),
                ('analysis_invalid', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assign_to_on_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.importbatch'),
        ),
        migrations.AddField(
            model_name='lead',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.importbatch'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='lead_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['reference_by', 'status'], name='lead_reference_status_idx'),
        ),
        migrations.AddField(
            model_name='importreviewrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_rows', to='crm.importbatch'),
        ),
        migrations.AddField(
            model_name='importreviewrow',
            name='existing_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='importrowerror',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='crm.importbatch'),
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_documents', to='crm.documenttype'),
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assignmenthistory',
            index=models.Index(fields=['lead', 'created_at'], name='assignhist_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmenthistory',
            index=models.Index(fields=['contact', 'created_at'], name='assignhist_contact_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmenthistory',
            index=models.Index(fields=['from_user', 'action'], name='assignhist_from_action_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['lead', 'created_at'], name='activity_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['contact', 'created_at'], name='activity_contact_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['current_assigned_to', 'status'], name='contact_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['reference_by'], name='contact_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['import_batch', 'current_assigned_to'], name='contact_batch_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='importreviewrow',
            index=models.Index(fields=['batch', 'decision'], name='review_batch_decision_idx'),
        ),
        migrations.AddIndex(
            model_name='importrowerror',
            index=models.Index(fields=['batch', 'stage'], name='rowerr_batch_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='leaddocument',
            index=models.Index(fields=['document_type', 'received'], name='leaddoc_type_received_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaddocument',
            constraint=models.UniqueConstraint(fields=('lead', 'document_type'), name='uniq_lead_document_type'),
        ),
    ]
