# Generated by Django 5.2.17 on 2026-09-26 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_segments_extra_data_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="e.g. phone model — for the admin's eyes only.", max_length=100)),
                ('android_device_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('pairing_code', models.CharField(blank=True, db_index=True, max_length=6)),
                ('pairing_code_expires', models.DateTimeField(blank=True, null=True)),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to instantly revoke a lost/replaced device.')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming')], max_length=10)),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('missed', 'Missed'), ('not_connected', 'Not Connected'), ('rejected', 'Rejected'), ('busy', 'Busy'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=15)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('external_call_id', models.CharField(db_index=True, max_length=150, unique=True)),
                ('source', models.CharField(default='android', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='crm.contact')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='crm.calldevice')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='crm.lead')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='calldevice',
            index=models.Index(fields=['pairing_code'], name='calldevice_pairing_idx'),
        ),
        migrations.AddIndex(
            model_name='calldevice',
            index=models.Index(fields=['staff', 'is_active'], name='calldevice_staff_active_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['staff', 'started_at'], name='callrecord_staff_started_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['phone_normalized'], name='callrecord_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['lead'], name='callrecord_lead_idx'),
        ),
    ]
