# Generated by Django 5.2.17 on 2026-09-28 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_contact_soft_delete_import_undo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('worked_duration', models.DurationField(blank=True, null=True)),
                ('attendance_status', models.CharField(choices=[('in_progress', 'In Progress'), ('full_day', 'Full Day'), ('half_day', 'Half Day'), ('short_day', 'Short Day')], default='in_progress', max_length=12)),
                ('auto_ended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'work_date'), name='uniq_attendance_user_work_date'), models.CheckConstraint(condition=models.Q(models.Q(('attendance_status', 'in_progress'), ('auto_ended', False), ('end_time__isnull', True), ('worked_duration__isnull', True)), models.Q(('end_time__isnull', False), ('worked_duration__isnull', False), models.Q(('attendance_status', 'in_progress'), _negated=True)), _connector='OR'), name='attendance_state_consistent'), models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('end_time__gte', models.F('start_time')), _connector='OR'), name='attendance_end_not_before_start')],
            },
        ),
    ]
