# Generated by Django 5.2.17 on 2026-09-30 04:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='n8n_payload_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='LeadSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_reference_id', models.CharField(help_text='Lead ID at the time, e.g. KM-1050.', max_length=30)),
                ('idempotency_key', models.CharField(help_text='lead-<Lead ID>; identical for every event of a Lead.', max_length=60)),
                ('event', models.CharField(default='lead_upsert', max_length=30)),
                ('reasons', models.CharField(blank=True, help_text='Comma-separated triggers merged into this event.', max_length=300)),
                ('force', models.BooleanField(default=False, help_text='Send even if nothing synced has changed.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='crm.lead')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='leadsync_due_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('lead',), name='uniq_pending_sync_per_lead'), models.UniqueConstraint(condition=models.Q(('status', 'processing')), fields=('lead',), name='uniq_processing_sync_per_lead')],
            },
        ),
    ]
